#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
#
# Regenerate tests/wire-invariants.inc — the checked-in wire record that
# tests/test_wire_invariants.c asserts the protocol's emission law against.
#
# WHY THIS EXISTS. 2026-08-20 a branch proposed that a REAC master emit every
# downstream frame TWICE (reac-pw #92, `REAC_PACER_TX_REPS 2`), on a reading of
# two MIRRORED captures taken raw: a tap that mirrors both directions of a port
# hands the capture each transiting frame twice, one copy clean and one carrying
# the two bytes of its own Ethernet FCS (include/reac/reac.h). The claim survived
# two triage passes on the strength of a commit message, because the facts it
# contradicted lived in prose and in a tool nobody was obliged to run. A fact we
# rely on and do not test is a fact anyone may overwrite.
#
# So the wire's own records come into the repository, and `make test` asserts
# against them with no corpus, no network and no capture on the machine.
#
# WHAT IS KEPT PER RECORD, and why it is enough: the source MAC (which peer),
# the 16-bit frame counter at frame[14:16] (the emission identity), the record's
# ORIGINAL length (the geometry — 52+36n is a clean REAC frame, +2 is the FCS
# residue of a mirror copy), the capture time relative to the first record, and
# a hash of the first 50 bytes (the header and the whole control block, which is
# what decides whether two records are the same frame twice or two frames).
#
# NO AUDIO CROSSES INTO THIS FILE. The hash is one-way and 50 bytes is the
# control block; not one sample of anyone's programme material is checked in.
#
#   tools/gen-wire-invariants.py <corpus-dir>      # rewrite tests/wire-invariants.inc
#
# <corpus-dir> is a checkout of the capture corpus (`reac-captures/captures`).
# The three captures below are named explicitly: two MIRRORED (the very files
# #92 measured, so the gate runs on the evidence that produced the claim) and one
# NON-MIRRORED (the control that the law is not an artefact of the dedup).

import sys, os, struct

CAPTURES = [
    # (id, filename, tap, declared rate, frames to keep)
    ("M200_48K_MIRROR",
     "m200i-s4000s-48k-mirror__matrix-m200-s4000-coldconnect-2026-07-24.pcap",
     "mirror", 48000, 1400),
    ("M5000_96K_MIRROR",
     "m5000-none-96k-mirror__matrix-m5000-s4000-unit2-coldconnect-2026-07-11.pcap",
     "mirror", 96000, 1400),
    ("M200_48K_CLEAN",
     "m200i-none-48k-clean__m200-probing-nobox-2026-07-11.pcap",
     "clean", 48000, 1000),
]

def records(path):
    with open(path, 'rb') as f:
        gh = f.read(24)
        magic, = struct.unpack('<I', gh[:4])
        if magic != 0xa1b2c3d4:
            raise SystemExit(f"{path}: not a native little-endian classic pcap ({magic:#x})")
        while True:
            rh = f.read(16)
            if len(rh) < 16:
                return
            ts, tus, incl, orig = struct.unpack('<IIII', rh)
            d = f.read(incl)
            if len(d) < incl:
                return
            yield ts * 1000000 + tus, orig, d

def fnv1a(b):
    h = 0x811c9dc5
    for x in b:
        h = ((h ^ x) * 0x01000193) & 0xFFFFFFFF
    return h

def main(corpus):
    out = []
    W = out.append
    W("/* GENERATED by tools/gen-wire-invariants.py -- DO NOT EDIT.")
    W(" *")
    W(" * Real traffic from the capture corpus, reduced to what the emission law")
    W(" * needs: source, counter, original length, relative time, header hash.")
    W(" * Read the generator for why each field is here and why no audio is.")
    W(" */")
    W("")
    W("struct wi_record {")
    W("\tuint8_t  src;      /* index into the capture's MAC table          */")
    W("\tuint16_t counter;  /* frame[14:16], little-endian                 */")
    W("\tuint16_t origlen;  /* the record's ORIGINAL on-wire length        */")
    W("\tuint32_t rel_us;   /* capture time, us since the first record     */")
    W("\tuint32_t hash;     /* FNV-1a over the first 50 bytes of the frame */")
    W("};")
    W("")
    W("struct wi_capture {")
    W("\tconst char *name;            /* the corpus file                    */")
    W("\tconst char *tap;             /* \"mirror\" or \"clean\"                */")
    W("\tint rate;                    /* the rate the capture was taken at  */")
    W("\tconst struct wi_record *rec;")
    W("\tunsigned n;")
    W("\tconst char *const *macs;")
    W("\tunsigned n_macs;")
    W("};")
    W("")
    caps = []
    for cid, fname, tap, rate, keep in CAPTURES:
        path = os.path.join(corpus, fname)
        macs, rows = [], []
        t0 = None
        for ts, orig, d in records(path):
            if len(d) < 16 or d[12] != 0x88 or d[13] != 0x19:
                continue
            if t0 is None:
                t0 = ts
            mac = ':'.join('%02x' % x for x in d[6:12])
            if mac not in macs:
                macs.append(mac)
            rows.append((macs.index(mac),
                         d[14] | (d[15] << 8),
                         orig,
                         ts - t0,
                         fnv1a(d[:50])))
            if len(rows) >= keep:
                break
        if not rows:
            raise SystemExit(f"{fname}: no REAC frames read -- refusing to write an empty fixture")
        span = rows[-1][3] / 1e6
        print(f"{fname}: {len(rows)} records, {len(macs)} sources, span {span:.2f}s", file=sys.stderr)
        W(f"/* {fname}")
        W(f" * tap={tap}  rate={rate}  records={len(rows)}  span={span:.2f}s  sources={len(macs)} */")
        W(f"static const char *const WI_{cid}_MACS[] = {{")
        for m in macs:
            W(f"\t\"{m}\",")
        W("};")
        W(f"static const struct wi_record WI_{cid}[] = {{")
        for r in rows:
            W("\t{%d,%d,%d,%d,0x%08xu}," % r)
        W("};")
        W("")
        caps.append((cid, fname, tap, rate, len(macs)))
    W("static const struct wi_capture WI_CAPTURES[] = {")
    for cid, fname, tap, rate, nmac in caps:
        W(f'\t{{ "{fname}", "{tap}", {rate},')
        W(f'\t  WI_{cid}, (unsigned)(sizeof WI_{cid} / sizeof WI_{cid}[0]),')
        W(f'\t  WI_{cid}_MACS, {nmac} }},')
    W("};")
    W("")
    dst = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "tests", "wire-invariants.inc")
    with open(dst, 'w') as f:
        f.write('\n'.join(out) + '\n')
    print(f"wrote {dst} ({os.path.getsize(dst)} bytes)", file=sys.stderr)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        raise SystemExit("usage: gen-wire-invariants.py <corpus-dir>")
    main(sys.argv[1])
